src/app/Home.tsx, src/components/atoms/Input/index.stories.tsx, src/components/atoms/Input/index.tsx, src/themes/colors.ts
=> feat: 어두운 배경의 Input 추가

src/components/molecules/TextArea/index.stories.tsx, src/components/molecules/TextArea/index.tsx
=> feat: TextArea 컴포넌트 생성

.storybook/main.ts, .storybook/public/images/sample/img_avatar.svg, next.config.js, package-lock.json, package.json, public/assets/image/img_avatar.svg, src/app/page.tsx, src/components/atoms/Avatar/index.stories.tsx, src/components/atoms/Avatar/index.tsx, src/components/molecules/TextArea/index.tsx
=> Feat/#10 Avatar 컴포넌트 생성

.storybook/preview.ts, src/app/page.tsx, src/components/atoms/index.ts, src/components/layout/Box/index.tsx, src/components/layout/index.ts, src/components/molecules/index.ts
- storybook 에서 보이는 화면을 상단의 메뉴를 통해 viewport 설정 가능
- ![](https://velog.velcdn.com/images/qmflf556/post/3e40db87-812d-4b36-84c7-28af110cbeae/image.png)
- 2개이상의 파일이 있는 모든 디렉토리의 경로는 index.ts 라는 파일이 관리합니다.
---
- Close #21
=> feat/#21 storybook viewport 설정, 절대경로 설정, Box 컴포넌트에 maxWidth, maxHeight 추가

src/app/page.tsx, src/components/atoms/Text/index.tsx, src/components/molecules/Label/index.stories.tsx, src/components/molecules/Label/index.tsx
- Label 컴포넌트는 p 태그로 전환한 Flex 컴포넌트입니다. 그래서 Box, FLex 에 있는 모든 속성을 적용할 수 있습니다.
- 만약 전체적으로 통일된 fontSize 를 적용하려면 Label 에 바로 fontSize 를 적용하면 됩니다.
- 만약 세부적으로 내부에 Text 별로 fontSize 를 적용하려면 각각 fontSize 를 적용해야 합니다.
- 현재 Label 에도, Text 에도 fontSize 를 적용하면 내부 Text 의 fontSize 가 적용되지 않는 Bug 가 있으나 하나의 p 태그 내에 폰트크기가 달라지는 경우가 많지 않은 것 같아 그대로 두었습니다.
- 자세한 예시는 Label 에 마우스를 호버하시면 확인할 수 있습니다.
---
- Close #24
=> feat/#24 Label 컴포넌트 생성

src/components/atoms/Text/index.tsx, src/components/molecules/Button/index.tsx, src/components/molecules/Label/index.tsx, src/components/organisms/ChatInfoCard/index.tsx, src/components/organisms/WorkerInfoCard/index.tsx, src/themes/fontSizes.ts
=> feat/#30-workerInfoCard, chatInfoCard 생성

src/app/page.tsx, src/components/atoms/Icon/index.tsx, src/components/layout/Box/index.tsx, src/components/organisms/AlertContainer/index.stories.tsx, src/components/organisms/AlertContainer/index.tsx, src/components/organisms/ChatInfoCard/index.stories.tsx, src/components/organisms/ChatInfoCard/index.tsx, src/components/organisms/TodayChatInfo/index.stories.tsx, src/components/organisms/TodayChatInfo/index.tsx, src/components/organisms/WorkerInfoCard/index.stories.tsx, src/components/organisms/WorkerInfoCard/index.tsx
feat/#42-TodayChatInfo&AlertContainer
feat/#42-storybook
---
- Close #42
=> mod/#42-chatInfoCard 수정

README.md, package-lock.json, package.json, src/app/layout.tsx, src/app/meeting/page.tsx, src/components/molecules/Button/index.stories.tsx, src/components/molecules/Calendar/index.tsx, src/components/templates/MeetingLayout/index.tsx, src/lib/mui.tsx
=> feat: MeetingApply 페이지 생성

src/app/login/page.tsx, src/app/meeting/page.tsx, src/app/page.tsx, src/app/signup/page.tsx, src/components/organisms/Login/index.tsx, src/components/organisms/MentoSearch/index.stories.tsx, src/components/organisms/MentoSearch/index.tsx, src/components/organisms/Signup/index.tsx, src/components/templates/LoginSignupLayout/index.tsx, src/components/templates/MyPageLayout/index.tsx
=> Feat/#62 login, signup page

src/chat/App.tsx
---
해결이 되었는지 여부를 배포해야 알 수 있어서 바로 이슈를 닫지 않겠습니다.
=> hotfix: port 번호 이슈 체크

src/components/molecules/Button/HyperLinkButton.tsx, src/components/organisms/Main/ChatInfoContainer/index.tsx, src/components/organisms/Main/IntroTextContainer/index.tsx, src/components/organisms/Main/ProcessInfoContainer/index.tsx, src/components/organisms/Main/PromoteTextContainer/index.tsx, src/components/organisms/Main/WorkerInfoContainer/index.tsx, src/components/organisms/WorkerInfoCard/index.tsx, src/components/templates/LoginSignupLayout/index.tsx, src/components/templates/MainLayout/MainBlackBackgroundLayout/index.tsx, src/components/templates/MainLayout/MainBlueBackgroundLayout/index.tsx
=> feat/#70-메인페이지 생성

README.md, package-lock.json, package.json, src/app/layout.tsx, src/app/seekerChat/page.tsx, src/app/workerChat/page.tsx, src/chat/App.tsx, src/chat/src/components/VideoRoomComponent.js, src/components/molecules/Button/HyperLinkButton.tsx, src/components/organisms/TodayChatInfo/index.tsx, src/lib/recoil.tsx, src/lib/useRequest.ts, src/types/data.d.ts, src/utils/state.ts
=> feat/#86 채팅방 입장하기

src/app/search/page.tsx, src/components/organisms/Main/WorkerInfoContainer/index.tsx, src/components/organisms/WorkerInfoCard/index.tsx
=> feat/#83-재직자 리스트 조회 API 연결 진행 중

.eslintrc.json, package-lock.json, package.json, src/chat/src/components/VideoRoomComponent.js, src/components/molecules/Input/index.tsx, src/components/organisms/BasicInfo/index.tsx, src/types/data.d.ts
=> feat#81 마이페이지 수정

src/app/layout.tsx, src/chat/src/registerServiceWorker.js
- PUBLIC_URL 을 배포 도메인으로 하여 시도
---
=> service worker 404 error

src/chat/src/components/VideoRoomComponent.js
- application server APPLICATION_SERVER_URL 수정
---
=> hotfix: deployment 주소 수정

src/app/search/page.tsx, src/app/workers/info/page.tsx, src/components/molecules/SearchInput/index.tsx, src/components/organisms/FilterModal/index.stories.tsx, src/components/organisms/FilterModal/index.tsx, src/components/organisms/MentoSearch/index.tsx, src/components/organisms/WorkerInfoCard/index.stories.tsx, src/components/organisms/WorkerInfoCard/index.tsx, src/components/templates/WorkerInfoListLayout/index.tsx, src/utils/state.ts
=> Feat/#91 WorkerInfoCard Component 기능 구현

src/app/search/page.tsx, src/components/molecules/DropdownButton/index.tsx, src/components/molecules/SearchInput/index.tsx, src/components/organisms/FilterModal/index.tsx, src/components/organisms/WorkerInfoCard/index.tsx, src/themes/colors.ts, src/utils/state.ts
=> mod/#110-FilterModal에서 적용하기 버튼을 눌렀을 때, 입력 정보 검색되도록 수정

src/app/workers/edit/page.tsx, src/components/organisms/AlertContainer/index.tsx, src/components/templates/LoginSignupLayout/index.tsx, src/components/templates/MyPageLayout/index.tsx
=> Mod/#112 3d shape 수정

src/app/search/page.tsx, src/components/molecules/DropdownButton/index.tsx, src/components/organisms/FilterModal/index.tsx, src/components/organisms/MentoSearch/index.tsx, src/components/organisms/WorkerInfoCard/index.tsx, src/components/templates/WorkerInfoListLayout/index.tsx, src/utils/state.ts
=> mod/#110-재직자 검색 기능 개선

README.md, package-lock.json, package.json, src/components/organisms/Main/ChatInfoContainer/index.tsx, src/components/organisms/Main/IntroTextContainer/index.tsx, src/components/organisms/Main/ProcessInfoContainer/index.tsx, src/components/organisms/Main/PromoteTextContainer/index.tsx, src/components/organisms/Main/WorkerInfoContainer/index.tsx, src/containers/AosContainer/index.tsx
=> feat: 메인페이지 scroll interaction 적용

src/chat/src/components/VideoRoomComponent.css, src/chat/src/components/chat/ChatComponent.css, src/chat/src/components/chat/ChatComponent.js, src/chat/src/components/toolbar/ToolbarComponent.css, src/chat/src/components/toolbar/ToolbarComponent.js
=> feat/#120 화상채팅 UI 수정

src/app/workers/info/page.tsx, src/components/molecules/Button/HyperLinkButton.module.css, src/components/molecules/Button/HyperLinkButton.tsx, src/components/organisms/TodayChatInfo/index.tsx
=> feat/#117 hyperlink button animation 추가

src/app/meeting/page.tsx, src/app/seekerChat/page.tsx, src/components/molecules/Button/HyperLinkButton.tsx
- #124 이슈번호 참고
---
- Close #124
=> bug/#124 상담요청시간 필수값으로 설정

src/app/workers/edit/page.tsx
- 비밀번호 변경사항 없을때 빈 문자열 전달
- #127 이슈참고
---
=> bug/#127 workers/edit bug 수정

src/app/seekerChat/page.tsx, src/components/organisms/ChatInfoCard/index.tsx
=> bug/#129 구직자의 커피챗 리스트에 대기중인 것도 표시

src/app/seekerChat/page.tsx, src/app/workerChat/page.tsx, src/app/workers/info/page.tsx, src/components/organisms/AlertContainer/index.tsx, src/components/organisms/Login/index.tsx, src/components/organisms/Signup/index.tsx, src/components/templates/MyPageLayout/index.tsx, src/components/templates/WorkerInfoListLayout/index.tsx
=> mod/#112-마이페이지, 멘토찾기 UI 수정

src/components/molecules/Header/index.tsx, src/components/molecules/SideMenu/index.tsx, src/components/organisms/Login/index.tsx, src/lib/sweetAlert.tsx
=> feat: sweet alert2 lib 생성, 로그아웃 기능 구현

src/app/search/page.tsx, src/app/seekerChat/page.tsx, src/app/workerChat/page.tsx, src/components/organisms/AlertContainer/index.tsx
=> mod: 나의 커피챗 리스트 오버플로우 제거

src/app/seekerChat/page.tsx, src/app/workerChat/page.tsx, src/app/workers/info/page.tsx, src/chat/src/components/VideoRoomComponent.js, src/components/organisms/ChatInfoCard/index.stories.tsx, src/components/organisms/ChatInfoCard/index.tsx
=> bug/#140 재직자의 커피챗 리스트에서도 수락 / 거절이 아닌 대기중으로 뜨는 문제 수정

package-lock.json, package.json, src/app/workers/info/page.tsx, src/components/templates/LoginSignupLayout/index.tsx, src/utils/state.ts
=> bug: recoil 상태 새로고침하면 사라지는 이슈 해결

src/app/meeting/page.tsx
=> bug/#142 예약 신청 페이지 오류 해결

src/app/workers/info/page.tsx
=> mod/#152-재직자 상세정보 수정

src/app/workers/info/page.tsx
=> mod: 재직자 상세 페이지 UI 수정 - 컴포넌트, 텍스트 가운데 정렬

src/components/organisms/BasicInfo/index.tsx, src/components/organisms/ChatInfoCard/index.tsx
=> mod/#157- BasicInfo hover기능 추가

src/app/meeting/page.tsx, src/app/workers/edit/page.tsx, src/app/workers/info/page.tsx, src/components/organisms/FilterModal/index.tsx, src/components/organisms/WorkerInfoCardSlider/index.tsx
=> mod: 커리업 신청 페이지, 재직자 상세 페이지 구조 수정 / slider dots 제거 / alert 동작 수정

src/app/meeting/page.tsx
meetingPage 타임버튼 오류 수정
---
- Close #162
=> bug/#162-meetingPage 타임버튼 오류 수정

src/app/seekerChat/page.tsx, src/app/workerChat/page.tsx, src/components/organisms/ChatInfoCard/index.tsx
=> feat: 거부된 채팅 리스트 보여주기

src/app/seekerChat/page.tsx, src/app/workerChat/page.tsx, src/components/templates/LoginSignupLayout/index.tsx, src/components/templates/MainLayout/MainBlackBackgroundLayout/index.tsx, src/components/templates/MainLayout/MainBlueBackgroundLayout/index.tsx, src/components/templates/MeetingLayout/index.tsx, src/components/templates/MyPageLayout/index.tsx, src/components/templates/WorkerInfoListLayout/index.tsx, src/containers/FloatingContainer/index.tsx
=> feat: 3d shape floating animation 생성
